#!/usr/bin/env python

import unittest
import rospy
import rostest
from arm_move.srv import restart, step

class TestCase(unittest.TestCase):
    def __init__(self,*args):
        super(TestCase,self).__init__(*args)
        self.restart = rospy.ServiceProxy('restart',restart)
        self.step = rospy.ServiceProxy('step',step)

        self.restart(clear_waypoints=False, box_x=0.15, box_y=0.0, box_z=0.025)
    
    def test_ground_collision(self):
        error_code = self.step(x=0.11175, y=0.0, z=-0.1, rx=0.0, ry=0.53735, rz=0.0, w=0.84336)
        self.assertEquals(error_code, -1)

    def test_successful_plan(self):
        error_code = self.step(x=.25, y=0.0, z=0.2, rx=0.0, ry=0.0, rz=0.0, w=1.0)
        self.assertEquals(error_code, 1)

if __name__ == "__main__":
    import rostest
    rospy.init_node('arm_test')
    rostest.rosrun('arm_move', 'arm_test', TestCase)





