#!/usr/bin/env python

import sys
import copy
import rospy
import moveit_commander
import moveit_msgs.msg
import geometry_msgs.msg
from math import pi
from std_msgs.msg import String
from moveit_commander.conversions import pose_to_list

def main():
    while True:
        moveit_commander.roscpp_initialize(sys.argv)
        robot = moveit_commander.RobotCommander()
        scene = moveit_commander.PlanningSceneInterface()

        rospy.sleep(2)

        group_name = "table"
        move_group = moveit_commander.MoveGroupCommander(group_name)

        p = geometry_msgs.PoseStamped()
        p.header.frame_id = robot.get_planning_frame()
        p.pose.position.x = 0.
        p.pose.position.y = 0.
        p.pose.position.z = 0.
        scene.add_box("table", p, (0.5, 1.5, 0.6))

if __name__ == '__main__':
    rospy.init_node('mover') 
    main()
    rospy.spin()