#!/usr/bin/env python

## FLIP NODE ##
'''
The flip node sends twist messages to the differential drive robot to make it drive forward, flip over, then continue 
to drive forward in the opposite direction. It accomplishes this by sending equal and opposite velocities.

Publishers:
    Name: diff/cmd_vel Type: geometry_msgs/Twist ~ Sends a twist message to the diff drive robot in gazebo
'''

import rospy
from geometry_msgs.msg import Twist,Vector3

def main():
    '''
    Publishes twist messages to make the diff drive robot drive forward and flip over. The velocities are looped so the robot drives
    forward for 5 seconds, then changes direction so the wheels spin with equal magnitude but opposite direction. After 3 of these
    cycles, the robot pauses for a second to help maintain control.
    '''
    pub = rospy.Publisher('diff/cmd_vel',Twist,queue_size = 10)
    while not rospy.is_shutdown():
        x = 0
        while x<3:
            twist_value = Twist(Vector3(x=1,y=0,z=0),Vector3(x=0,y=0,z=0))
            pub.publish(twist_value)
            rospy.sleep(5)

            twist_value = Twist(Vector3(x=-1,y=0,z=0),Vector3(x=0,y=0,z=0))
            pub.publish(twist_value)
            rospy.sleep(5)
            
            x += 1
        
        twist_value = Twist(Vector3(x=0,y=0,z=0),Vector3(x=0,y=0,z=0))
        pub.publish(twist_value)
        rospy.sleep(1)

if __name__ == '__main__':
    rospy.init_node('mover') 
    main()
